#端口
server:
  port: 10000
  servlet:
    context-path: /order
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://grgbanking:grgbanking@127.0.0.1:12000/eureka,http://grgbanking:grgbanking@127.0.0.1:13000/eureka
    #注册和开启检索
    register-with-eureka: true
    fetch-registry: true

#名称
spring:
  application:
    name: springcloud-order
