#端口
server:
  port: 9000
  servlet:
    context-path: /item

#名称
spring:
  application:
    name: springcloud-item
  cloud:
    zookeeper:
      connect-string: 192.168.44.3:2181

#eureka
#eureka:
#  client:
#    service-url:
#      defaultZone: http://grgbanking:grgbanking@127.0.0.1:12000/eureka,http://com.grgbanking:com.grgbanking@127.0.0.1:13000/eureka
#    #注册
#    #开启检索
#    fetch-registry: true
#    register-with-eureka: true
#  #instance:
#    #prefer-ip-address: true #将自己的ip注册到eureka服务中
#    #ip-address: 127.0.0.1
#    #instance-id: ${spring.application.name}###${server.port} #指定实例id
